version: 1
disable_existing_loggers: False
formatters:
  simpleFormatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simpleFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simpleFormatter
    filename: ${LOG_DIR}/training.log
    mode: a

loggers:
  exampleLogger:
    level: INFO
    handlers: [fileHandler]
    propagate: no

root:
  level: INFO
  handlers: [consoleHandler]